Tablist:
  Header:
    - '&7&m                                      &r'
    - '&b&lServer'
    - '&fWelcome, {player-name}'
    - "&r"
  Footer:
    - '&r'
    - '&fexample.com'
    - '&7&m                                      &r'

Motd:
  - "&a&lServer &7[1.8-1.19]"
  - "&7» &2&lInformative Message Here"

Server-Brand: "vanilla"

Server-Status:
  Online: "&f{replacement-0}/{replacement-1}"
  Whitelist: "&eWhitelisted"
  Offline: "&cOffline"

Server-Aliases:
  Lobby: "Lobby"
  Hub: "Lobby"

Limbo-Schematic-File: ./plugins/BasicsBungee/limbo.schem
Limbo-Spawn-X: 23
Limbo-Spawn-Y: 40
Limbo-Spawn-Z: 17
Limbo-Spawn-Yaw: 90
Limbo-Spawn-Pitch: 0