Tablist:
  Header:
    - '&7&m                                      &r'
    - '&b&lServer'
    - '&fWelcome, {player-name}'
    - "&r"
  Footer:
    - '&r'
    - '&fexample.com'
    - '&7&m                                      &r'

Server-Brand: "vanilla"

Server-Aliases:
  Lobby: "Lobby"
  Hub: "Lobby"